---

  - include: install_packages.yml
  
  - name: Deploy confiurations
    template:
      src: templates/nginx.j2
      dest: /etc/nginx/nginx.conf
    notify: restart nginx 
  - name: Deploy Welcome.html
    copy: 
      src: Welcome.html 
      dest: /usr/share/nginx/html   
